Controllers/ExhibitController.cs
using ExhibitionApp.Data;
using ExhibitionApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ExhibitionApp.Controllers
{
    [Authorize(Roles = "Storekeeper")]
    public class ExhibitController : Controller
    {
        private readonly ExhibitionAppDbContext _dbContext;

        public ExhibitController(ExhibitionAppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult GetAllExhibits()
        {
            List<Exhibit> allExhibits = _dbContext
                .Exhibits
                .Include(e => e.Authors)
                .ToList();

            return View(allExhibits);
        }

        public IActionResult Details(long? id)
        {
            var exhibitToShow = _dbContext
                .Exhibits
                .Include(e => e.ExhibitType)
                .Include(e => e.Authors)
                .Include(e => e.Warehouse.Address.Street.City)
                .FirstOrDefault(e => e.Id == id);

            return View(exhibitToShow);
        }

        [HttpGet]
        public IActionResult CreateExhibit()
        {
            SelectList exhibitTypes = new SelectList(_dbContext.ExhibitTypes, "Id", "TypeName");
            ViewBag.ExhibitTypes = exhibitTypes;

            var warehousesFromDb = _dbContext
                .Warehouses
                .Include(w => w.Address.Street.City);
            SelectList warehouses = new SelectList(warehousesFromDb, "Id", "Address");
            ViewBag.Warehouses = warehouses;

            var authorsFromDb = _dbContext.Authors;
            SelectList authors = new SelectList(authorsFromDb, "Id", "Pseudonym");
            ViewBag.Authors = authors;

            return View();
        }

        [HttpPost]
        public IActionResult CreateExhibit(ExhibitViewModel exhibitModel)
        {
            var exhibit = exhibitModel.Exhibit;
            exhibit.Warehouse = _dbContext.Warehouses.FirstOrDefault(warehouse => warehouse.Id == exhibit.WarehouseId);
            exhibit.ExhibitType = _dbContext.ExhibitTypes.FirstOrDefault(exhibitType => exhibitType.Id == exhibit.ExhibitTypeId);
            exhibit.Authors = _dbContext.Authors.Include(a => a.Exhibits).Where(author => exhibitModel.SelectedAuthorsId.Contains(author.Id)).ToList();

            _dbContext.Exhibits.AddRange(exhibit);
            _dbContext.SaveChanges();

            return RedirectToAction("GetAllExhibits");
        }

        public IActionResult Edit(long? id)
        {
            SelectList exhibitTypes = new SelectList(_dbContext.ExhibitTypes, "Id", "TypeName");
            ViewBag.ExhibitTypes = exhibitTypes;

            var warehousesFromDb = _dbContext
                .Warehouses
                .Include(w => w.Address.Street.City);
            SelectList warehouses = new SelectList(warehousesFromDb, "Id", "Address");
            ViewBag.Warehouses = warehouses;

            var authorsFromDb = _dbContext.Authors;
            MultiSelectList authors = new MultiSelectList(authorsFromDb, "Id", "Pseudonym");
            ViewBag.Authors = authors;

            var exhibitToUpdate = _dbContext.Exhibits.Include(e => e.Authors).FirstOrDefault(e => e.Id == id);
            ViewBag.ExhibitId = id;

            ViewBag.CreationDate = exhibitToUpdate.CreationDate.ToString();
            ViewBag.ArrivalDate = exhibitToUpdate.ArrivalDate.ToString();

            var model = new ExhibitViewModel()
            {
                Exhibit = exhibitToUpdate,
                SelectedAuthorsId = exhibitToUpdate.Authors.Select(e => e.Id).ToList(),
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ExhibitViewModel exhibitModel)
        {
            var exhibitToUpdate = exhibitModel.Exhibit;

            _dbContext.Attach(exhibitToUpdate);

            exhibitToUpdate.Warehouse = _dbContext.Warehouses.FirstOrDefault(warehouse => warehouse.Id == exhibitToUpdate.WarehouseId);
            exhibitToUpdate.ExhibitType = _dbContext.ExhibitTypes.FirstOrDefault(exhibitType => exhibitType.Id == exhibitToUpdate.ExhibitTypeId);
            exhibitToUpdate.Authors = _dbContext
                .Authors
                .Include(a => a.Exhibits)
                .Where(author => exhibitModel.SelectedAuthorsId.Contains(author.Id))
                .ToList();

            _dbContext.Entry(exhibitToUpdate).State = EntityState.Modified;
            _dbContext.SaveChanges();

            ClearAuthors(exhibitModel.SelectedAuthorsId, exhibitToUpdate);
            return RedirectToAction("GetAllExhibits");
        }

        private void ClearAuthors(List<long> selectedId, Exhibit entry)
        {
            var authors = _dbContext.Authors.Include(a => a.Exhibits);

            foreach (var author in authors)
            {
                if (!selectedId.Contains(author.Id) && author.Exhibits.Any(ex => ex.Id == entry.Id))
                {
                    author.Exhibits.Remove(entry);
                }
                else if (selectedId.Contains(author.Id) && !author.Exhibits.Any(ex => ex.Id == entry.Id))
                {
                    author.Exhibits.Add(entry);
                }
            }

            _dbContext.SaveChanges();
        }

        public IActionResult Delete(long? id)
        {
            var exhibitToDelete = _dbContext.Exhibits.Find(id);
            _dbContext.Exhibits.Remove(exhibitToDelete);

            _dbContext.SaveChanges();

            return RedirectToAction("GetAllExhibits");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExhibitionApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExhibitionApp.styles.css" asp-append-version="true" />
    <link href="https://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/css/bootstrap-multiselect.css" rel="stylesheet" type="text/css"/>

</head>
<body>
    <header>
        <navigation>
            <ul class="nav nav-pills flex-column mb-auto">
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
                    <div class="container-fluid">
                        @if (User != null && User.Identity.IsAuthenticated && User.IsInRole("Manager"))
                        {
                            <a class="navbar-brand text-white" asp-area="" asp-controller="Exhibition" asp-action="GetAllExhibitions">Менеджер: @User.Identity.Name</a>
                        }
                        else if (User != null && User.Identity.IsAuthenticated && User.IsInRole("Storekeeper"))
                        {
                            <a class="navbar-brand text-white" asp-area="" asp-controller="Exhibit" asp-action="GetAllExhibits">Работник склада: @User.Identity.Name</a>
                        }
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        @if (User == null || !User.Identity.IsAuthenticated)
                        {
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item mx-1">
                                        <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "Poster" ? "nav-link text-white active" : "nav-link text-white")
                                           asp-area=""
                                           asp-controller="Poster"
                                           asp-action="UpcomingExhibitions">
                                            PERMM Афиша
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="text-end">
                                <li class="nav-item mx-1">
                                    <a class="btn btn-success"
                                       asp-area="Account"
                                       asp-controller="UserLogin"
                                       asp-action="Index">
                                        Войти
                                    </a>
                                </li>
                            </div>
                        }
                        @if (User != null && User.Identity.IsAuthenticated && User.IsInRole("Manager"))
                        {
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item mx-1">
                                        <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "Exhibition" ? "nav-link text-white active" : "nav-link text-white")
                                           asp-area=""
                                           asp-controller="Exhibition"
                                           asp-action="GetAllExhibitions">
                                            Выставки
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="text-end">
                                <li class="nav-item mx-1">
                                    <a class="btn btn-danger"
                                       asp-area="Account"
                                       asp-controller="UserLogin"
                                       asp-action="UserSignOut">
                                        Выйти
                                    </a>
                                </li>
                            </div>
                        }

                        @if (User != null && User.Identity.IsAuthenticated && User.IsInRole("Storekeeper"))
                        {
                            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item mx-1">
                                        <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "Exhibit" ? "nav-link text-white active" : "nav-link text-white")
                                           asp-area=""
                                           asp-controller="Exhibit"
                                           asp-action="GetAllExhibits">
                                            Экспонаты
                                        </a>
                                    </li>
                                    <li class="nav-item mx-1">
                                        <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "Author" ? "nav-link text-white active" : "nav-link text-white")
                                           asp-area=""
                                           asp-controller="Author"
                                           asp-action="GetAllAuthors">
                                            Авторы
                                        </a>
                                    </li>
                                    <li class="nav-item mx-1">
                                        <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "Address" ? "nav-link text-white active" : "nav-link text-white")
                                           asp-area=""
                                           asp-controller="Address"
                                           asp-action="GetAllAddresses">
                                            Адреса
                                        </a>
                                    </li>
                                    <li class="nav-item mx-1">
                                        <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "Warehouse" ? "nav-link text-white active" : "nav-link text-white")
                                           asp-area=""
                                           asp-controller="Warehouse"
                                           asp-action="GetAllWarehouses">
                                            Склады
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            <div class="text-end">
                                <li class="nav-item mx-1">
                                    <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "ReferenceTable" ? "nav-link text-white active" : "nav-link text-white")
                                       asp-area=""
                                       asp-controller="ReferenceTable"
                                       asp-action="GetAllExtraTables">
                                        Справочники
                                    </a>
                                </li>
                            </div>

                            <div class="text-end">
                                <li class="nav-item me-2">
                                    <a class=@(ViewContext.RouteData.Values["controller"].ToString() == "Report" ? "nav-link text-white active" : "nav-link text-white")
                                       asp-area=""
                                       asp-controller="Report"
                                       asp-action="Index">
                                        Отчеты / Импорт
                                    </a>
                                </li>
                            </div>

                            <div class="text-end">

                                <li class="nav-item mx-1">
                                    <a class="btn btn-danger"
                                       asp-area="Account"
                                       asp-controller="UserLogin"
                                       asp-action="UserSignOut">
                                        Выйти
                                    </a>
                                </li>
                            </div>
                        }
                    </div>
                </nav>
            </ul>
        </navigation>
    </header>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.rawgit.com/davidstutz/bootstrap-multiselect/master/dist/js/bootstrap-multiselect.js"></script>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Информационная система учета экспонатов выставки - <a asp-area="" asp-controller="Home" asp-action="Privacy">Что-то</a>
        </div>
    </footer>
    

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>